import ReduxProvider from './redux/provider/ReduxProvider'

import { Inter } from 'next/font/google'

import Navbar from './components/Navabar'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hasin Ishrak',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ReduxProvider>
        <Navbar/>
        
      {children}
        
        </ReduxProvider>
        </body>
    </html>
  )
}
